### ISSUE TITLE
Figures for manuscript

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#106]
Cartoons:
1. Cartoon regarding biology (may not be necessary)
2. Graphical abstract (**DONE** apart from some minor retouches)
3.  Picture of tHMM mathematical model (**DONE**)
Graphs:
4. Scaling figure **(DONE)**
4a. scaling across lineage length (**DONE**)
4b. scaling across number of lineages (**DONE**)
5. KL divergence figure **(DONE)**
6.  AIC figure **(DONE)**

**Comment by namn12** [comment]
i dont think the cartoon is necessary. though i do feel like there will be more figures later on we will add (cell cycle / wet lab). maybe we should close this and open a new one when the time comes
