### ISSUE TITLE
Introduction paragraph on prior work

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#116]
We should have a paragraph on prior applications of tHMMs since there are one or two. I would also mention linkage analysis here, and analysis of incomplete penetrance in family trees.

**Comment by shak360** [comment]
**Are linkage studies boring?**
https://www.nature.com/articles/ng0793-213
_"Most important, using linkage as a foundation, the search for actual genes by positional cloning will accelerate and become more accurate. The eventual discovery of the ataxia genes will lead to better speculations about pathogenesis and ultimately to much needed treatment and prevention. Will these genes show deletions, duplications, point mutations, triplet repeat expansions, imprinting and anticipation?"_

**Genetics of Type 1A Diabetes**
https://www.nejm.org/doi/full/10.1056/NEJMra0808284?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%3dpubmed
_ A disease allele that occurs frequently in the population and that has a large effect on disease risk is unlikely to exist. At the opposite end of the spectrum, a disease allele that is rare and has a small effect size is likely to exist but is unlikely to be found — and such alleles would be of limited public health interest. In general, linkage studies are most effective in disorders in which disease
alleles are anticipated to have a large effect size but occur infrequently. Association studies are most effective for the detection of alleles that occur frequently but have a small effect size. These are general trends, and there are no specific boundaries in efficacy between the two approaches._

**Comment by shak360** [comment]
**Deciphering Latent Growth-States from Cellular Lineage Trees**
https://www.biorxiv.org/content/10.1101/488981v1
_"Then, we propose an estimation algorithm of the latent states from lineage trees based on an estimation-maximization (EM) algorithm, which we call Lineage EM algorithm (LEM). We verify the effectiveness of LEM by using synthetic data. Finally, we apply LEM to a lineage tree of E. coli, and identify a latent three-dimensional continuous state, one component of which encodes the information on the inheritance of the states and the replicative capabilities over generations. The inferred dynamics suggests that the homeostasis and heterogeneity of the division times are controlled with multiple time scales."_

**Modelling Stem Cells Lineages with Markov Trees**
https://link.springer.com/chapter/10.1007/978-3-642-04031-3_21
_"We estimated the hidden Markov tree model parameters using the variationalBayesian approach with smoothed probabilities. The VBS-HMT model is applied to incomplete stem cells lineage tree data. The experimental data used in this study consists of 30 lineage trees, where just the type of cells at the start and at the end of each tree is known. The model developed here confronts the challenge of stem cell lineage tree reconstruction by determining the most likely state tree corresponding to the observed stem cell lineage tree."_

**Comment by aarmey** [comment]
Crouse et al.in 1998

**Comment by aarmey** [comment]
Concannon et al. NEJM, 2009

**Comment by shak360** [comment]
We are motivated by the need to better quantify cell drug response by addressing the problem of cell plasticity and heterogeneity. In particular, we want to study the effects of stochastic transitions between individual cell states with low probabilities but have significant substantial effects on the resulting heterogeneous population's response to drug. Genetic _association_ studies marked by efforts like the Cancer Cell Line Encyclopedia, which use population-level samples to find common risk factors with smaller effect sizes, are valuable nut lack the ability to find rare and meaningful transitions. In genetic studies, _linkage_ analyses have found success in situations where the risk factors being sought have large effect sizes but are relatively rare. These linkage studies use pairs of affected relatives like siblings to identify genes that are shared more frequently among those who exhibit a known phenotype [concannon2009genetics]. In the cellular case, linkage analyses rely on lineage trees to identify groups of related cells or subpopulations. In general, hidden Markov models (HMMs) let one infer cell state from indirect measurements. By operating on a lineage tree, tHMMs enable us to perform a single cell linkage analysis of cellular heterogeneity.

Other computational models for cell lineages have yet to incorporate a tHMM that provides a full spectrum of underlying cell states based on phenotypic measurements for every member in a lineage. Tree-based models utilizing linkage and inheritance information have previously been employed in phylogeny discovery and evolutionary analyses,[@Bykova] and such models have been validated in molecular systems, such as identifying chromatin hidden states by observing histone modifications.[@Kuchen; @Biesinger] Previously, stem cell lineages have been modeled by hidden Markov trees for the purpose of reconstructing the lineage tree based on the observations of the level of expression of a particular cell surface antigen. [@vbemHMT] More recently, Others have shown success in inferring the latent states of bacterial cells and the associated state-switching dynamics from lineage tree data. [@nakashima2018deciphering] In general, hidden Markov tree algorithms have been used for a multitude of purposes, from document image classification to understanding plant-tree architecture. [diligenti2003hidden; durand2005analysis] Many of these tHMMs use inference (expectation-maximization and belief propagation) algorithms for tree restoration based originally from the algorithms created for hidden Markov chains, with minor modifications to how state information is propagated through the tree; namely, Crouse et al developed an upward-downward recursion expectation-maximization algorithm different from the original forward-backward algorithm usually associated with HMMs for finding wavelet coefficients in statistical signal processing. [crouse1998wavelet; durand2004computational]

None of these models, however, have been developed for cell phenotype analysis with potential application in tumor-specific cancer therapy, nor have any of these models been provided open source for use by the scientific community. We hope to provide phenotypic measurements of cell fitness as a novel methodology for the following bedside and bench applications: (1) analyzing cells in heterogeneous cancer by providing unseen features of the inherent properties of cellular functioning and (2) providing biomedical researchers an analytical tool for understanding cellular heterogeneity within their experiments. In essence, this work will assist researchers, pathologists, oncologists, and the like in distinguishing the structure of heterogeneous cell subpopulations and identifying single-cell response to cancer therapy. 

@aarmey  @namn12

**Comment by namn12** [comment]
i feel like we should do 3 sections in intro:
cancer heterogeneity -> linnkage analysis -> thmm

**Comment by namn12** [comment]
PR 129
