### ISSUE TITLE
Fill out author roles

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#117]
The author contributions statement should list what each person did. Look [here](http://ijfs.ir/uploads/Pdfz/Author%20contributions2.pdf) for an example.

**Comment by namn12** [comment]
@aarmey can you provide the names of the authors who performed the experiments at ohsu for cell phase data we will be using

**Comment by aarmey** [comment]
Don't worry about adding them for the moment. I'll have to check with them.
