### ISSUE TITLE
Notebook guide from master doesn't run

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#138]
<img width="1079" alt="Screen Shot 2019-07-12 at 3 51 49 PM" src="https://user-images.githubusercontent.com/2065146/61162345-04558b00-a4bd-11e9-8081-34b31584cfa8.png">

**Comment by Farnazmdi** [comment]
I removed the function Dr. Meyer, it wasn't working for the depth generating cells, and since we are going to build most of the things again, I removed it to avoid those errors for now.  I will correct this file right away @aarmey

**Comment by shak360** [comment]
I already fixed this @Farnazmdi Don't worry
