### ISSUE TITLE
Expectation step of BW

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#142]
Are you sure we can just look at lineages with an altered likelihood during the expectation step?

https://github.com/meyer-lab/lineage-growth/blob/9403afbf7d8f4d93076af521604d649bb49c45be/lineage/BaumWelch.py#L117

**Comment by shak360** [comment]
So this was there prior to when we did estimation across all lineages (back when each lineage was used to find each of the state distributions per lineage). I guess now it doesn't make sense to do a 'per lineage' stopping condition.

**Comment by aarmey** [comment]
Ok, I'll remove it in a forthcoming PR.

**Comment by shak360** [comment]
However, the likelihood calculation is per lineage and we don't have a likelihood of population method (unless it makes sense to just add the likelihood of each lineage).

**Comment by aarmey** [comment]
You can just sum the log-likelihoods to get that of the population. (We're implicitly assuming separate lineages are independent, but I think that's reasonable.) The current stopping condition is fine, though; once fitting converges nothing should change, so both give you the same outcome.
