### ISSUE TITLE
the new approach

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/lineage-growth#146]
@shak360 I wrote what we discussed yesterday, please review it. Haven't added emissions to it, just kept the function on the notebook. 
Here is the [.py file](https://github.com/meyer-lab/lineage-growth/blob/new_approach/lineage/new_approach.py)

and the [notebook](https://github.com/meyer-lab/lineage-growth/blob/new_approach/new_approach.ipynb) (forced it)

**Comment by shak360** [comment]
great next step is to write a test file to test these functions in the same way cell node is tested. we should also add a lineage id member variable to cell as we should be able to fit and analyze multiple lineages belonging to one populations. ill begin to clean up the variable names and check for certain things as you work on it. good work.

**Comment by shak360** [comment]
just keep the notebook locally for now, we don't have to add more notebooks to the repository

**Comment by shak360** [comment]
ok make sure to pull before you begin working, added more functions similar to cell node and added documentation. made some code more pythonic and named some variables more clearly.

**Comment by shak360** [comment]
https://github.com/meyer-lab/lineage-growth/blob/new_approach/lineage/Emissions.py

**Comment by Farnazmdi** [comment]
[](https://github.com/meyer-lab/lineage-growth/pull/28/commits/576e677b0de72ae6b8b78d5c8027beb88eb4f4cc) @shak360

**Comment by shak360** [comment]
- change distribution file to just have one big distribution process
- consequently change how LineageTree works
- remove multiple distribution functionality from tHMM (all the various if conditions concerning `FOM`)
- move LineageTree to a new file
- write unit tests for both classes/files
 - improve documentation for both files, docstrings, pylint, the files, make files consistent with variable names and other conventions
- add missing functionality from CellNode and Lineage and Lineage_utils to the new approach files
- keep updating unit tests
- add a new intro block to the guide to code notebook detailing how our lineage generate process works
- add methods to prune tree (will most likely have to meet for this
-- I'm thinking we add something like `subtree_prune_rule` to Distributions which can either be `None` or a conditional that returns True or False when looking at a cell and it tells another function `prune` to remove the subtree

@Farnazmdi feel free to add things or de-prioritize things

**Comment by Farnazmdi** [comment]
this is a good list, I will write the unittests.
Another thing to add was `generation` to the function, so we will have a list of cells in the same generation.

* documentation improvement, updating unittests are continuously needed! Let's do them for every new function we write. I think we could do any of them sooner or later but a rough order could be like: 

1. adding anything needed from CellNode and Lineage_utils to the new approach
2. adding estimators of distributions
3. dealing with `pruning`
4. updating tHMM based off of the new approach
5. replacing the index finding with `enumerate` everywhere needed.
6. Writing a guide to the new approach.

We could also meet later today to formulate the pruning. @shak360

**Comment by shak360** [comment]
I added the estimators so don't have to worry about that; it's in the StateDistribution.py. Also i was thinking the emissions dictionary is just one ordered dictionary of objects, because we no longer need an inner one. It would just be one ordered dictionary of stateDistribution objects. 

Im free after 6ish to meet. If youd like to start thinking, first i was thinking we make PrunedLineageTree a subclass of LineageTree (We'd have to learn how inheritance works in python) and secondly, we would add, to the distribution object, a member function called prune_rule and all it does is return True or False if a certain cell and its subtree need to be cut. I haven't fully fleshed out these ideas but we can do that when we meet. Lemme know what you think or if you have a better idea.

**Comment by Farnazmdi** [comment]
Ok, great, thanks.

 I am also free after 6, I will think about it, too and we can finalize together.
