### ISSUE TITLE
Change figure code to adapt to `new_approach` in a new branch

### ISSUE THREAD

**Issue by namn12** [meyer-lab/lineage-growth#151]

**Comment by shak360** [comment]
figure 1: graphical abstract diagram
figure 2: cell data
figure 3: cell data
figure 4: model mathematical diagram
figure 5: examples of lineages (1 state, 2 state, 3 state) w/ transition matrices vs. pruned/unpruned (just plotting different lineages)
figure 6: accuracy/parameter estimation over increasing number of cells, pruned vs. unpruned
figure 7: accuracy/parameter estimation over increasing number of lineages, pruned vs unpruned
figure 8: estimating over cell data, results

**Comment by shak360** [comment]
https://docs.python.org/2/library/multiprocessing.html

**Comment by Farnazmdi** [comment]
@shak360  has Dr. Meyer confirmed this list of figures?

**Comment by shak360** [comment]
@Farnazmdi Sort of, not really. We briefly discussed it last meeting but nothing was set in stone. Feel free to update it how you see fit. I'll add @aarmey to this conversation.

**Comment by aarmey** [comment]
This will get us close. It’s best to get these figure elements down, then we can rearrange them easily.

**Comment by shak360** [comment]
Figure 6 (near final): 
![image](https://user-images.githubusercontent.com/20716101/64083594-d3345280-ccd6-11e9-938a-5c471a0c5799.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/64292882-3fee5d80-cf20-11e9-8c22-da2aff5e5682.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/64293703-03bbfc80-cf22-11e9-8f77-e6660d95f9c4.png)

**Comment by Farnazmdi** [comment]
figure 8, AIC:
![image](https://user-images.githubusercontent.com/34812750/65461229-62311800-de08-11e9-9cb1-2cfa66a04851.png)

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/65660200-c3acde80-dfe2-11e9-9ffb-3b1a03e1720c.png)

**Comment by aarmey** [comment]
This issue is done now, no?
