### ISSUE TITLE
Add parallel processing to figure creation

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#178]
Add parallel processing to figure creation.

**Comment by aarmey** [comment]
@shak360 @Farnazmdi there's not much that can be done to speed up builds outside of this, so this might be best for tackling next. If every model evaluation is handled in parallel you should see a really large speedup (~12-20X).

**Comment by Farnazmdi** [comment]
@aarmey: 

> `Analyze()` fits the model to a new set of random data X number of times. The issue is about running each of those trials (within a single plot) in parallel.

**Comment by shak360** [comment]
Should we do this prior to calculating the PDF/ sampling a distribution using numba (issue #211)?

**Comment by aarmey** [comment]
Sure. This should be easier to implement.

**Comment by shak360** [comment]
@aarmey I finished changing the figures and writing a new function that can be parallelized for each datapoint on the figure function. That function to be parallelized can be found here: 

https://github.com/meyer-lab/lineage-growth/blob/79443e417868514edda9eb2dd0dcc847f419df82/lineage/Analyze.py#L57

All it does is it runs `Analyze` over a list of populations (lists of lineages). It stores a tuple of results from each `Analyze` run in a list, named `output`, which is just a list of tuples. It's just one foor loop.

The figures are changed to accomodate this, so most everything should work. I can fix the notebook in PR #193 once we add the parallel processing to PR #220 . Let me know if you have any questions.

**Comment by aarmey** [comment]
Any chance we can fix and merge this before I make changes? That'll help ensure I don't break things.

**Comment by shak360** [comment]
Yep, that makes sense to me. It seems like it's taking more than an hour to run figures 5 and 6. Do you mind if I just comment those figures out for the sake of finishing the PR?

**Comment by aarmey** [comment]
That's fine.

**Comment by aarmey** [comment]
FYI I've put what I *think* will work on the `parallel-Accuracy` branch.

**Comment by shak360** [comment]
Done see #222
