### ISSUE TITLE
CellTracker

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/lineage-growth#208]
@aarmey  I have tried working with cell tracker which is an extension in MATLAB, but I couldn't get it work with our images. It say the input should be a "multi-image TIFF" -- it doesn't accept a set of images. I tried to make a multi-image TIFF with these two softwares :1. Advanced TIFF editor plus, 2. TIFF image printer, but now it says "could not perform operation (update the slice window)". I searched for it, someone else had this issue, but no one had provided any solutions for it. 
I am not sure what I can do, do you have any suggestions?

**Comment by aarmey** [comment]
Is Cell Tracker what we discussed with Dr. Shah? I thought everything in Cell Profiler is implemented in Python...

**Comment by Farnazmdi** [comment]
Ohhh I haaad to ask you the name of it, I wasn't sure about the name of this. Sorry, yes I misunderstood and wasted a lot of time.

**Comment by aarmey** [comment]
It was Cell Profiler, with NucleAIzer.

http://www.nucleaizer.org

**Comment by Farnazmdi** [comment]
Thank you very much. I will work with this.
