### ISSUE TITLE
Have pdf calculated through a fused, numba-compiled function

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#211]
Fitting spends most of its time calculating the pdf:

https://github.com/meyer-lab/lineage-growth/blob/cfad4a2951a4148c4cc863f325ca7008e1d08cfc/lineage/StateDistribution.py#L27

The scipy functions broadcast over observations in a simple loop. This can probably be much more efficient if we just calculate it ourselves.

**Comment by shak360** [comment]
See #228 Done.
