### ISSUE TITLE
Plotting lineages

### ISSUE THREAD

**Issue by Farnazmdi** [meyer-lab/lineage-growth#213]
Here is what I have from the MATLAB package to plot the lineage:
![tree1](https://user-images.githubusercontent.com/34812750/72475065-0287bf80-379f-11ea-961e-e37f510c707e.jpg)
I couldn't plot more than 1 lineage in one plot yet. Do you think something like this is enough or we want something more complicated? @aarmey @shak360

**Comment by shak360** [comment]
That looks great, in my opinion. Can you give me the name of the MATLAB toolbox/package?

**Comment by Farnazmdi** [comment]
It is called matlab-tree [here](https://github.com/tinevez/matlab-tree)

**Comment by aarmey** [comment]
This looks great. Surprised there's nothing similar in python...

**Comment by Farnazmdi** [comment]
If it was easy enough I was willing to do it for google summer of code :))

**Comment by aarmey** [comment]
Hmm... seems like a good idea!

**Comment by shak360** [comment]
We've tried `plotly`, and a combination of `matplotlib`, `networkx`, and the same program used to generate the profiling charts (`graphviz`)?. This looks more like a lineage tree than the other tries did.  Don't know if there's any other plotting modules, or tree data libraries.

**Comment by Farnazmdi** [comment]
Yeah! I couldn't find anything like it in any other software or languages!

**Comment by shak360** [comment]
There's this:

http://etetoolkit.org/docs/latest/index.html

**Comment by Farnazmdi** [comment]
Yep, I had tried it!

**Comment by aarmey** [comment]
This looks promising: https://github.com/jangevaare/PhyloTrees.jl

**Comment by Farnazmdi** [comment]
Exactly what we were looking for!

**Comment by Farnazmdi** [comment]
I think I will wait until we figure out how the data and importing would look like and then I will address this. Creating the tree is dependent on how we have the data. 
I looked for some tool to translate (or import) python classes to Julia, but it doesn't look like really feasible. 
That way, I can use the effort that imports the data into python, and using the same pattern to di it in Julia, and build `Struct` with constructors (instances) and just write a recursive-ish function to plot the tree.

**Comment by Farnazmdi** [comment]
#426
