### ISSUE TITLE
Profile again

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#227]

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/73793713-cb804a80-475b-11ea-98cb-f32a458375e3.png)

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/74979040-a853cd00-53e2-11ea-8ca9-fec3a9d14451.png)

**Comment by shak360** [comment]
Looks like the hold is up in pruning lineages, which isn't utilized in the model anyway, only in lineage synthesis. This is to be expected because this is done recrusively through the tree and walks through the tree several times.

**Comment by shak360** [comment]
It was suggested that we individually profile the figure creation process (not the testing) as I usually do. We can identify which figure takes the most time. My bet is on figure 5 (AIC).

**Comment by shak360** [comment]
To profile:
```bash
python3 -m cProfile -o profile genFigures.py 5
gprof2dot -f pstats --node-thres=5.0 profile | dot -Tsvg -o profile.svg
```

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/75200825-a314bc00-571b-11ea-8068-b6aebe4d03f7.png)
AIC figure

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/75201207-b5dbc080-571c-11ea-814a-73b2629197da.png)
Figure 4 (analyzing over an increasing number of lineages or starting cells)

**Comment by shak360** [comment]
Seems like making pruning faster would be the best bet in terms of speeding up figures.

**Comment by shak360** [comment]
Wrote a short script to generate all figures at once and then profiled it:
![image](https://user-images.githubusercontent.com/20716101/75288951-301a4c80-57d2-11ea-9f77-2024040f804e.png)

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/75290253-d7987e80-57d4-11ea-8c82-e6e824a21f50.png)
Figure 6 (performance vs distribution divergence)

**Comment by aarmey** [comment]
@shak360 note that you have to remove any multithreading to get accurate profiling. `thread.lock` just means the thread is waiting for another to finish.

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/75597293-93fa7a80-5a49-11ea-87b6-5bcb951668e3.png)

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/75597646-80e8aa00-5a4b-11ea-861e-5b295798d638.png)

**Comment by aarmey** [comment]
`beta_parent_child_func` is a good candidate for numba.

**Comment by aarmey** [comment]
@shak360 please profile again. My changes have hopefully reduced some of the slower parts.

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/75711367-2897ef00-5c7b-11ea-86a0-be5e475f0151.png)
Figure 3 (after recent speed changes)

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/75713196-3a2ec600-5c7e-11ea-8f84-83be255007eb.png)
FIgure 4 (after recent changes)

**Comment by aarmey** [comment]
Is there a need to copy the tree before pruning? Why not just prune the original?

**Comment by shak360** [comment]
I was just paranoid about losing information, or data that was generated. I thought it was better to keep both an unpruned and pruned copy of the tree in memory, regardless of the user's final choice. I like the idea of just having one tree, where the pruned (the cells that didn't survive) are just "hidden".

**Comment by aarmey** [comment]
Great. I just made a change that should speed up `get_nonroot_gammas()`. Once you've changed the pruning re-profile—I think all the slow spots in the current profiling will be gone.

**Comment by aarmey** [comment]
I think we can easily speed this up by 3-5X still.

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/76692228-baefa980-6610-11ea-80eb-7d6144de096b.png)
(figure 3)

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/76692276-77496f80-6611-11ea-874f-ccbdd843a756.png)
(figure 4)

**Comment by aarmey** [comment]
Think we're great at this point.
