### ISSUE TITLE
model performance vs relative heterogeneity 

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#230]
Hi @jclagarde ,

We'll try to do this next assignment in two to three sub-assignments (I'd also like for you to push the changes to the Guide, if you haven't done so already). Recall that the main goal is to add another figure to the project. 

**Figure 5. Model performance vs the relative amount of heterogeneity**

Things you should know before you begin:
You can look at the figures generated by our project in one of two ways:
1. Access our CI client Jenkins. CI stands for continuous integration and is a software tool designed for managing large codebases or code that is continuously changing. You can access it here: 

https://transduc.seas.ucla.edu/job/meyer-lab/job/lineage-growth/job/master/

Previous "builds" or versions of our projects (and other projects from Dr. Meyer's lab) can be found here. Feel free to play around. Do not click on anything that looks dangerous. You can see the most updated "builds" or versions of our manuscript/figures at the top of that page. You can also see how various branches of our project can affect these builds when you examine those branches on Jenkins. I can show you how to navigate this website more in person.

2. On your own Aretha server account. First, run through your basic git commands:
```
git status
git checkout master
git pull
git branch jc-fig
git checkout jc-fig
```
Go to your lineage folder and then up one folder (that is, you should see a file called `makefile`, the Guide that you've been working on, and the `lineage` folder itself). Check if there exists a folder called `output`. If not, open up terminal, `cd` into this `lineage-growth` directory (that is, if you `ls -ltr`, you should see the `makefile`, the guide, and the `lineage` folder) or whatever you have it named as, and then type in `make`. What this does is, it runs the commands listed in the makefile. It does many things that are relevant for users, but for now, we can focus on how it makes figures. Once `make` is done running, run `cat -n makefile` in the terminal; this displays the content of the makefile, which is just a textfile of shell commands, onto the terminal. You can also open the `makefile` in the text editor by double-clicking on the file on the left file explorer bar. 

Tasks:

0. Because we're going to add another figure, let's add the number `7` to line 7 in the makefile, to the variable `flist`. Save the file and exit. Recall your git commands for adding, commiting, and pushing:
```
git add -A
git commit -m "adding 7 to makefile"
git push
```
Recall that the the first `push` on a new branch will require you to set the origin. Follow what git prompts you to do.

1. Because you ran `make`, there should a folder named `output` in your `lineage-growth` directory (the directory above `lineage`). Go into output (`cd output`) and delete (`rm figure3.svg`) any one of the figures and run `make` again. It should err out. Figure out what the error is and resolve it (what directory do you have to be in to run`make`?). Run `make` again when you've figured out what's wrong.

2. Go into the `output` directory and delete again a figure using either the file explorer bar on the left or using the terminal (`rm output/figure3.svg`). If you want to remake the particular figure that you just deleted, then run `make output/figure3.svg`. This runs the figure making code _for that particular figure_, and doesn't run through the rest of the makefile. Don't hesitate to ask any questions if you encounter an error.

3. Because we added an additional figure to the `flist` in the `makefile`, we need to add a file called `figure7.py` to our `lineage-growth/lineage/figures/` folder. Let's make figure 7 be a blank figure for now. To do so, open up `figure1.py`, which is also a blank figure, copy the code, and paste it into `figure7.py` making sure that all the comments that need to be changed are changed. If you run the relevant command to make figure 7, then you should see a blank figure inside the `output` folder. Add, commit, and push your changes.

4. Let's move our current figure 5 to figure 7 and figure 7 to figure 5. I'm doing this because it flows better in terms of a story for the data and model that we are trying to present: the current figure 5 talks about how a user should be using our model, but the figure we are trying to create talks more about the data the user should feed into our model. It makes sense to me that the figure we are trying to create now should come earlier. We can do this by renaming files. Let's rename figure5.py to figure8.py. Rename figure7.py to figure5.py. Finally rename figure 8.py to figure7.py. Rewrite any comments in both of these files that should be changed because of the new figure numbers they now represent. Note that we can't simply just rename figure5.py to figure7.py immediately because it's bad practice and can lead to several errors if you have two files of the same name in the same directory. Add, commit, and push your changes.

5. Run `make` again. Note that nothing is happening. Note that these figure%.svg files first need to be deleted if they are to be made by running `make`. They won't be made if they exist already. Because making these figures on your server account can take a while, we can check Jenkins. Navigate to the Jenkins list of branches for our project: https://transduc.seas.ucla.edu/job/meyer-lab/job/lineage-growth/ and find your branch. You can then see the results of your changes to the figures on the list of last successful artifacts on the top of the page.

6. While you're on Jenkins, I want you to look at the other figures that are available. I want you to write down what you think should be changed in each of the figures (if any). This includes things like formatting, labels, fonts, titles, text, colors, etc. You can add this list to the issue under #226. Next time we meet, we can go through this list and change them together for the figures. 

Let me know when you're done with the above, and we can meet in person when you are. If you are done early, I'd like for you to complete this tutorial: https://matplotlib.org/3.1.3/tutorials/introductory/lifecycle.html#sphx-glr-tutorials-introductory-lifecycle-py We can also go through the finished tutorial of this in person, if you have any questions.

**Comment by shak360** [comment]
If you're done with the assignment above, @jclagarde, and the tutorial, I want you to complete the following in a Jupyter notebook:

1. Copy the following code into a cell, and add comments to the lines of code that don't make sense to you. If the line of code makes sense to you, you should be able to explain why it is or isn't necessary for the given output, and how changing it might affect the output. I also want you to fill out the lines in the for loop. If a line of code doesn't make sense, and you've exhausted any internet resource that could explain it (i.e., matplotlib or python documentation), feel free to ask me questions.
```python
import numpy as np
from matplotlib import gridspec, pyplot as plt
%matplotlib inline
plt.rc('font', **{'family': 'sans-serif', 'size': 10})
# for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
plt.rc('xtick', **{'labelsize': 'medium'})
plt.rc('ytick', **{'labelsize': 'medium'})
import seaborn as sns
df = sns.load_dataset("anscombe")
print(df)

x0=df.loc[ 0:10]["x"][:].tolist()
x1=df.loc[11:21]["x"][:].tolist()
x2=df.loc[22:32]["x"][:].tolist()
x3=df.loc[33:43]["x"][:].tolist()
y0=df.loc[ 0:10]["y"][:].tolist()
y1=df.loc[11:21]["y"][:].tolist()
y2=df.loc[22:32]["y"][:].tolist()
y3=df.loc[33:43]["y"][:].tolist()
list_of_xs = [x0,x1,x2,x3]
list_of_ys = [y0,y1,y2,y3]
colors=['r','b','g','y']


f1 = plt.figure(dpi=250)
# Make grid
gridd=(2,2)
gs1 = gridspec.GridSpec(*gridd)
# Get list of axis objects
ax = [f1.add_subplot(gs1[x]) for x in range(gridd[0] * gridd[1])]
# Complete the for loop below
for i in range(4):
    # first, set the x-limits of each subplot to [0,20]

    # second, set the y-limits of each subplot to [0,15]
    
    # third, fill out the arguments for this scatter function based on the following requirements
    # give it black edge colors
    # give it circular markers
    # make the color of the marker in the subplot the same as the color indexed by the list named colors (that is, index the colors list above by the index variable i)
    # make the figure datapoints have an alpha transparency value of 0.666...
    # spaces are given for you in the following scatter call to write these arguments out
    ax[i].scatter(list_of_xs[i], list_of_ys[i],    ,    ,    ,    )

plt.tight_layout()
plt.show()
```

The resulting plot should look like this (for reference):
![image](https://user-images.githubusercontent.com/20716101/75489364-f169cb00-5966-11ea-8862-863d2e391360.png)

2. In a new cell, copy the following code, and fill out the lines such that you can recreate the figure below, _to the best of your ability_. You will need the linked csv file (dropbox link below) to be in the same folder as your jupyterlab notebook that you're working in.
```python
### Don't edit this code below ###
import csv

csv_reader = csv.reader(open('data_HR.csv'))
Y = np.expand_dims(np.squeeze(np.asarray(list(csv_reader), dtype=int)), axis=1)
X = np.expand_dims(np.linspace(start=0, stop=24, num=len(Y)), axis=1)
plt.figure(1, figsize=(12.5, 7.5), dpi=200)
### Don't edit this code above###

# Start here:
# this scatter call needs additional arguments:
# give it black edge colors
# give it circular markers
# make the marker color #8795E8
# set the alpha transparency to be 0.5
# spaces are given for you in the following scatter call to write these arguments out
plt.scatter(X, Y,    ,    ,    ,    )
# What else needs to be done to make the figure look like the reference figure?
# x-ticks

# y-ticks

# a background grid, with an alpha transparency of 0.25

# x-limits

# y-label

# x-label


### Don't edit this code below ###
plt.show()
### Don't edit this code above###
```

The csv for this figure can be downloaded here: https://www.dropbox.com/s/yej7f2872vjh4u8/data_HR?dl=0

The resulting plot should look like this (for reference):
![image](https://user-images.githubusercontent.com/20716101/75494726-b3be6f80-5971-11ea-9085-aecd672a851c.png)

3. Not using code, think about how the figure we plan to make should look like (consider making a mockup). Use the existing figures on Jenkins as a reference. How many subplots should it have? What are the independent and dependent variables? (x- and y-axis values) Recall that we are modeling accuracy vs the relative proportion of states. How should we measure the imbalance of states in a population? Use figures 3, 4, and 6 as references.

(Navigate back to your branch `jc-fig`)
4. Fix figure 6 such that the violin plots appear on the LEFT-hand side instead of its current placement on the right-hand side. Remember that you'll have to first navigate to figure6.py, find the function that draws the figures, and then change which plot is made first or on the left. You should have to change fewer than 5 lines of code for this. Recall how to make figures (delete the existing figure6.svg file, and then run make `output/figure6.svg` or simply navigate to your branch on Jenkins after adding, committing, and pushing).

5. The way that our figures are generated (for the most part) are made in 3 big steps:
- 1. create the subplots
- 2. run the model and find the values to plot
- 3. plot them
The part that changes the most between figure to figure is step 2. Step 2 can be expanded into a another set of steps:
-- 2.1. generate a list of populations to analyze (populations that usually vary with our independent variable)
-- 2.2. analyze the populations
-- 2.3. collect and store the dependent variables (usually accuracy, and parameter estimates)

Find the functions in figures 3 and 4 that carry out these steps. (Start with the three lines of code in the function named `makeFigure`) 

6. (Hard) What aspect of the population of lineages creation process should be varied to vary the proportion of states? Consider fixing the initial probability vector, which is the probability that the first state is a certain state (i.e., `pi=[0.5 0.5]` implies that it is equally likely for either state to be the first state). Let's also fix the emissions (the state distributions that define the states). This leaves the transition matrix. Let's also fix other variables of the lineage creation process (experiment time, pruning, etc.). How do we change the transition matrix such that we can start with populations with a high imbalance of states and then end with populations with a good balance of states? Answering the following might help:
- Does a population with a transition rate matrix of `T=[[0,1],[0,1]]` have a high imbalance of states or low. If there is an imbalance, which state dominates?
- What about a transition rate matrix of `T=[[0.5,0.5],[0.5,0.5]]`?

(In the Jupyter notebook)
7. (Hard) Write a function that returns proper transition matrices between `T=[[0,1],[0,1]]` and `T=[[0.5,0.5],[0.5,0.5]]`. It should return a list of transition matrices where `list_of_Ts[0] = [[0,1],[0,1]]` and `list_of_Ts[-1] = [[0.5,0.5],[0.5,0.5]]`. Recall that the `-1` index means the last entry. This function has no other constraints other than the transition matrices inside the returned list as output must be proper (Recall from your first assignment that this means that the rows should add up to 1, and shouldn't contain negative values). Consider that the function should take in as input something that changes the size of the list; that is, it should take in something that either gives me a small list (a list with only those two entries) or a large list with many transition matrices in between. This argument could be an `adder` value. For example, if the adder value was set to be 0.25, then the returned list could be `list_of_Ts[0] = [ [[0,1],[0,1]], [[0.25,0.75],[0.25,0.75]], [[0.5,0.5],[0.5,0.5]] ]`. In general, this process is called **interpolation** and is a tool used across engineering and scientific disciplines.

**Comment by shak360** [comment]
@jclagarde 

For the final part of the assignment, please complete the following (should take no more than an hour):

Always do your beginning git commands:
```
git status
git checkout master 
git pull
```

1. Navigate to the branch I made: `sv-treeFiddy`.
2. Open `figure5.py`
3. Complete the tasks listed at `# TODO` comments (line no. 35 and 52).
4. 
```
git add -A
git commit -m "work"
git push
```
5. Once you're satisfied with your work, open a Pull Request on GitHub. Add me and Dr. Meyer as reviewers. Add me as an assignee. If the build fails, see why it's failing and fix it accordingly. If you need help, let me know.

**Comment by shak360** [comment]
@jclagarde Also I'd like to see some of the answers you came up with for the previous assignments. I understand that it might not be feasible or in our best interests to meet in person, so feel free to just paste whatever you can in this issue.

**Comment by jclagarde** [comment]
@shak360 Got it. I will work on it sometime tonight!

**Comment by jclagarde** [comment]
![IMG_0812](https://user-images.githubusercontent.com/54101546/76480932-5abcf580-63cd-11ea-80c6-427406a3626e.jpg)
![IMG_0813](https://user-images.githubusercontent.com/54101546/76480934-5c86b900-63cd-11ea-9cc4-ffd299558b89.jpg)

**Comment by shak360** [comment]
Do you have the code and the images for the figures I asked you to reporduce as well?

**Comment by jclagarde** [comment]
@shak360 yes, sorry for the late reply. 

`import numpy as np
from matplotlib import gridspec, pyplot as plt
%matplotlib inline
plt.rc('font', **{'family': 'sans-serif', 'size': 10})
# for Palatino and other serif fonts use:
# rc('font',**{'family':'serif','serif':['Palatino']})
plt.rc('xtick', **{'labelsize': 'medium'})
#sets the x axis label and tick marks
plt.rc('ytick', **{'labelsize': 'medium'})
#sets the y axis label and tick marks
import seaborn as sns
#seaborn is a library of statistical graphing
df = sns.load_dataset("anscombe")
print(df)
#loads the example dataset from Anscombe's Quartet (data sets with descriptive statistics)

#df.loc accesses values from data frame from row_x to row_y
x0=df.loc[ 0:10]["x"][:].tolist()
#accesses x values for first graph
x1=df.loc[11:21]["x"][:].tolist()
#accesses x values for second graph
x2=df.loc[22:32]["x"][:].tolist()
#accesses x values for third graph
x3=df.loc[33:43]["x"][:].tolist()
#accesses x values for fourth graph
y0=df.loc[ 0:10]["y"][:].tolist()
#accesses y values for first graph
y1=df.loc[11:21]["y"][:].tolist()
#accesses y values for second graph
y2=df.loc[22:32]["y"][:].tolist()
#accesses y values for third graph
y3=df.loc[33:43]["y"][:].tolist()
#accesses y values for fourth graph

list_of_xs = [x0,x1,x2,x3]
list_of_ys = [y0,y1,y2,y3]
colors=['r','b','g','y']
#creates lists from the data frame values and assigns colors to graphs


f1 = plt.figure(dpi=250)
# Make grid
gridd=(2,2)
gs1 = gridspec.GridSpec(*gridd)
# Get list of axis objects
ax = [f1.add_subplot(gs1[x]) for x in range(gridd[0] * gridd[1])]
# Complete the for loop below
for i in range(4):
    # first, set the x-limits of each subplot to [0,20]
    ax[i] = plt.subplot(2, 2, i+1)
    ax[i].set_xlim(0,20)
    # second, set the y-limits of each subplot to [0,15]
    ax[i].set_ylim(0,15)
    # third, fill out the arguments for this scatter function based on the following requirements
    # give it black edge colors
    # give it circular markers
    # make the color of the marker in the subplot the same as the color indexed by the list named colors (that is, index the colors list above by the index variable i)
    # make the figure datapoints have an alpha transparency value of 0.666...
    # spaces are given for you in the following scatter call to write these arguments out
    ax[i].scatter(list_of_xs[i], list_of_ys[i] , edgecolors = 'k' , marker = 'o' , c = colors[i], alpha = 0.666  )

plt.tight_layout()
plt.show()`

**Comment by shak360** [comment]
Hmmm, it might be easier to just take screen shots of the code and the plots they produce
