### ISSUE TITLE
Test case for Viterbi

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#248]
We currently don't test Viterbi at all. Probably the easiest test would be that the state assignments are maximum likelihood. In other words, get the Viterbi result, and then compare it to ~10 other state assignments. Check that it's higher likelihood than all the others.

**Comment by Farnazmdi** [comment]
I am not sure how to calculate the likelihood of a sequence of states, is that alright to compare their accuracy?

**Comment by Farnazmdi** [comment]
I mean comparing the accuracy of the sequence of states that Viterbi predicts, and the other 10 sequences that we generate as random.

**Comment by aarmey** [comment]
@shak360 can help with this.

**Comment by Farnazmdi** [comment]
So far,
1. Shakthi: 
Using the joint probability function to find the likelihood.
![image](https://user-images.githubusercontent.com/34812750/76654956-6de4d800-6529-11ea-866d-0e7a1f80013d.png)
I don't know what the second term is (\prod_{n=2: N} P(z_n | z_p_n)) in terms of the vectors we have from tHMMobj.

2. Farnaz: 
![image](https://user-images.githubusercontent.com/34812750/76655101-d0d66f00-6529-11ea-97f9-92e6f50ffa74.png)
The quantities above don't seem to be dependent on the sequence of state assignments! When I try it with the predicted Viterbi states, and when I try a random sequence of states with the same vector size, there is no difference in the likelihood.

Both make sense to me, but I'm stuck in both!

**Comment by Farnazmdi** [comment]
#268

**Comment by aarmey** [comment]
Great! Last thing we can take care of is having the AIC plot use this likelihood. Then we can close this.

**Comment by Farnazmdi** [comment]
I'm on it.

**Comment by Farnazmdi** [comment]
Does this make sense?!
![image](https://user-images.githubusercontent.com/34812750/76686147-9b3b8f80-65d6-11ea-9bf1-f982f12f7865.png)

**Comment by Farnazmdi** [comment]
This is when we sum up the state and the previous likelihood. Although, the last one should be the joint likelihood.
![image](https://user-images.githubusercontent.com/34812750/76686272-7b589b80-65d7-11ea-9300-a609c9496286.png)

**Comment by aarmey** [comment]
The likelihood for AIC should incorporate everything—observations, transitions, etc. It should be the same likelihood that is maximized with Viterbi.

**Comment by Farnazmdi** [comment]
@aarmey The first one is the joint probability of states and observations. It doesn't look right for the second and third plot I guess.
I will make the PR and ask @shak360 to take a look at it whenever convenient.

**Comment by aarmey** [comment]
It looks reasonable to me. Yes, open a PR.

**Comment by Farnazmdi** [comment]
#270
