### ISSUE TITLE
Update figure captions

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#258]
Could someone update the figure captions to what each figure and plot now shows? This will greatly help me work through the text.

**Comment by Farnazmdi** [comment]
I'm on it.

**Comment by Farnazmdi** [comment]
Figures need attention I guess. They have changed a little...

**Comment by Farnazmdi** [comment]
some notes for us:
1. In figure 2, *maybe* the susceptible and resistant cells have changed places in part b, and d.
2. In figure 2, we need to enumerate a,b,c,d.
3. In figure 3, transition matrix estimation (f) looks like it is estimating it wrong... needs improvement(?)
4. In figure3, state assignment accuracy (d) all are 100%, a little weird...
5. In figure 3, the title and ylabel for part (e) should be the initial probability matrix.
6. In figure3, the ylabel of part (d) has an extra \
7. I guess figure 3 and 4 are combined! Figure 3 was supposed to be for a single state, and figure 4 was supposed to be for a 2-state population. 
The whole results need to be rewritten.

**Comment by shak360** [comment]
Figure 3 should _not_ have an f subplot. It should be named as the pi initial probability vector and it's being estimated poorly because it's testing on single lineages. It doesn't need that f subplot. And the accuracy for figure 3 is fine, it tends to get 100% all lineage sizes.

**Comment by Farnazmdi** [comment]
I thought it is single lineage, though with 2 states, so estimation for parameters have to change accordingly then.

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/76465905-c5593b80-63a3-11ea-945e-09e6b3180aea.png)
Yea each of these points are single lineages of increasing length

**Comment by Farnazmdi** [comment]
#260

**Comment by shak360** [comment]
#281
