### ISSUE TITLE
Gamma parameter values

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#289]
Some of the gamma parameter values are from last year. Farnaz has some newly calculated ones that are worth using.

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/79286837-aeac7580-7e76-11ea-8945-5108e8a2ba2b.png)

Here are the parameters.
In the near future, I will keep the shape constant across all the trials, but for now and for our purpose here I guess this suffices.

**Comment by Farnazmdi** [comment]
The numbers along with the names are just the concentration in nanomolar.
