### ISSUE TITLE
Diagrams/cartoons for figures

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#300]
@jclagarde you can update us here.

**Comment by jclagarde** [comment]
<img width="542" alt="Screen Shot 2020-04-28 at 1 16 24 AM" src="https://user-images.githubusercontent.com/54101546/80464018-05da2d80-88ee-11ea-8ceb-95912dd25b20.png">
<img width="535" alt="Screen Shot 2020-04-28 at 1 16 33 AM" src="https://user-images.githubusercontent.com/54101546/80464020-083c8780-88ee-11ea-9436-c52845211797.png">
<img width="519" alt="Screen Shot 2020-04-28 at 1 16 40 AM" src="https://user-images.githubusercontent.com/54101546/80464023-08d51e00-88ee-11ea-836f-4475a4a5c164.png">
<img width="509" alt="Screen Shot 2020-04-28 at 1 16 52 AM" src="https://user-images.githubusercontent.com/54101546/80464028-096db480-88ee-11ea-9072-be4188eff38a.png">
<img width="533" alt="Screen Shot 2020-04-28 at 1 16 59 AM" src="https://user-images.githubusercontent.com/54101546/80464031-096db480-88ee-11ea-99dd-cf435f9b6e37.png">

**Comment by aarmey** [comment]
[Figures Final.pdf](https://github.com/meyer-lab/lineage-growth/files/4581570/Figures.Final.pdf)

**Comment by shak360** [comment]
Closed with #412
