### ISSUE TITLE
Make a guide for creating custom state distributions

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#312]
Copy out StateDistribution as written in current files, then create Gaussian emission as new State distribution. Finally, with this new state distribution, generate and then fit a lineage. Show that the inferred result is roughly correct.

**Comment by aarmey** [comment]
https://github.com/meyer-lab/lineage-growth/blob/master/lineage/states/StateDistribution.py

**Comment by shak360** [comment]
![image](https://user-images.githubusercontent.com/20716101/81754953-47311800-946c-11ea-9157-96337a6e6735.png)
