### ISSUE TITLE
Introduction proofing

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#318]
Please go through and proof what we have. It'd also help me to have comments before each paragraph that succinctly state what is the overarching point of the paragraph. For example, before a paragraph going through prior work using tHMMs: "Prior work using tHMMs."

You can add comments like this: `<!-- This is a comment. -->`

**Comment by aarmey** [comment]
Once I merge the `linting` branch, there will also be a `spell.txt` build product that should catch spelling errors.

**Comment by Farnazmdi** [comment]
Sure. Will do.
