### ISSUE TITLE
Importing Heiser lab lineage format

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#319]
I think we have a couple of these Excel files around. Given they've done some more extensive tracking, we probably want to just make a method for importing these data.

**Comment by shak360** [comment]
How do you feel about having an intermediate format (in XML or JSON) for representing lineage data, that can be easily read by our code, and input data from users should be formatted in before using it as input for our code? @aarmey @Farnazmdi 

![image](https://user-images.githubusercontent.com/20716101/82254090-1129e300-9907-11ea-899e-0ac8b4e720d6.png)

So we have a XML Input Output code which would have things like:
1. a format checker that checks whether a user's lineage in XML format is capable of being read
2. converts the XML document into tHMM readable lineages
3. converts the tHMM output lineages into an XML document
4. plots lineages using the XML document (like PhyloTrees does)

**Comment by aarmey** [comment]
Could we just serialize/pickle our existing lineage class? An intermediate format, unless closely tied to our existing format, would just create more conversion steps.

**Comment by shak360** [comment]
Done with #405 #401
