### ISSUE TITLE
Enhance printing of `StateDistribution` objects

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#331]
https://github.com/meyer-lab/lineage-growth/blob/5f97dff2c04282a46737456e1f2a957539db6aef/lineage/states/StateDistribution.py#L89

The line above uses a f string (see here: https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python) to print out `StateDistribution` objects. 

Note that it individually lists out the state distribution's parameters. However, those parameters are already collected in a list stored in `self.params`.

https://github.com/meyer-lab/lineage-growth/blob/5f97dff2c04282a46737456e1f2a957539db6aef/lineage/states/StateDistribution.py#L19

This should be changed to where only this list of parameters is printed out (This change should be implemented in all the `StateDistribution`s.

**Comment by jclagarde** [comment]
is it correct to use the list self.params for the StateDistribution1? I'm unsure because the parameters used in it aren't the same as self.params

**Comment by shak360** [comment]
Can you show me what you're referring to?

**Comment by jclagarde** [comment]
Line 76 on StateDistribution1.py

<img width="831" alt="Screen Shot 2020-05-27 at 2 37 05 PM" src="https://user-images.githubusercontent.com/54101546/83074766-9019cc80-a027-11ea-965a-18b151bf8ea4.png">

**Comment by shak360** [comment]
Yeah, but the `self.params` for that is

https://github.com/meyer-lab/lineage-growth/blob/a09018d6757415e04e2f7dbc75286d88bc069ed7/lineage/states/StateDistribution1.py#L14

Aren't they the same? Am I missing something?

**Comment by shak360** [comment]
All you'd have to do is change it to the following for all the state distributions:

```python
return f"State object w/ parameters: {self.params}"
```

**Comment by jclagarde** [comment]
Ohhhh, you're right they are the same. I had thought I was supposed to replace all of that with this self.params = [self.bern_p, self.gamma_a, self.gamma_scale]

**Comment by jclagarde** [comment]
I pushed a commit to statedistribution.py and statedistribution1.py, lmk if there's anything else I need to change

**Comment by shak360** [comment]
Nope, looks good to me.
