### ISSUE TITLE
Making a base StateDistribution class, and then inheriting it for other specific StateDistributions

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#332]
Inheritance lets you define a common class, which you can then extend for more specific versions of that class.

https://www.w3schools.com/python/python_inheritance.asp

Overriding or overwriting original implementations of functions in the base class, can let you write different versions of functions like `.rvs()`, `.pdf()`, `.estimator()`, and others.

We can also inherit functions like `__repl__` which will be the same amongst all StateDistribution classes.

**Comment by shak360** [comment]
https://www.python-course.eu/python3_inheritance.php

**Comment by aarmey** [comment]
Also, rather than that separate `init_E_...()` method (don't remember exactly what it was called). This should just be the defaults in the class initializer.

**Comment by aarmey** [comment]
I think StateDistribution is sufficiently simplified that this might not make much of a difference?

**Comment by shak360** [comment]
Yea, I agree, might be over-engineering if this was done.
