### ISSUE TITLE
The state distributions should be directly tested

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#339]
This can simply be generating a series of observations and checking you get an accurate parameter estimation out. You could also check that if `gamma` is reduced for all the observations identically, that you get the same answer.

**Comment by aarmey** [comment]
A good way to do this for all StateDistribution types would be create a bunch of cells using the default initializer, then fit these and check you get an estimate close to the real center.

**Comment by Farnazmdi** [comment]
Handling empty observations means that if the observation arrays are empty, it should return some error?

**Comment by aarmey** [comment]
Actually, you can ignore that about empty observations. Shakthi and I ended up discussing that in a PR, and decided we can set it up so that estimators can assume they will always get observations.

**Comment by Farnazmdi** [comment]
I see. OK, so I will add the tests from the other issue and tag Shakthi and then you for review.
