### ISSUE TITLE
Dangerous exception handling in state distribution

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#366]
Under what circumstance is this exception supposed to be hit? If it is for an empty state, let's just check for that in LineageTree and initialize the StateDistribution if that's the case. I'm concerned that, by catching BaseException, we might hide other errors. This will also simplify the code as the state distributions will be able to assume they will always get cells.

https://github.com/meyer-lab/lineage-growth/blob/c7d57f2b68d7b546e6b074be59f9505ff7a6966e/lineage/states/StateDistributionGamma.py#L63

**Comment by shak360** [comment]
In much much earlier versions of the code, this exception would be hit, but I have a feeling it's not being hit as much (if at all) anymore. I can see if it's being hit. It might be a superfluos exception.

**Comment by aarmey** [comment]
Ok, I'll remove it.
