### ISSUE TITLE
Setup test that 3-, 4-, 5-state model successfully fit

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#373]
I think everything we have just tries a 2-state model right now. It's definitely possible there are indexing/other errors with higher numbers of states.

**Comment by Farnazmdi** [comment]
Should the number of states be some kind of argument?

**Comment by aarmey** [comment]
It already is. The issue here is we never test that the code works with 3, 4, 5... states.

**Comment by Farnazmdi** [comment]
Tests... Sure ok.
