### ISSUE TITLE
Implement flexible emissions using probabilistic language

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#55]
`pymc3` might be easiest for this as it has helpers for censoring, distributions, etc. This could also be done more directly in TensorFlow, pytorch, autograd, etc.

**Comment by shak360** [comment]
http://delivery.acm.org/10.1145/3320000/3314642/pldi19main-p645-p.pdf?ip=128.97.129.109&id=3314642&acc=OA&key=CA367851C7E3CE77%2E79535EF926D6BC05%2E4D4702B0C3E38B35%2EE959BD37CA561672&__acm__=1563056431_f53e0c7c86c2913d226d9e898b3d484a

Newest probabilistic programming language: Gen

**Comment by aarmey** [comment]
So many of these now...
