### ISSUE TITLE
Implement cell cycle reporter emissions

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/lineage-growth#56]
The Heiser lab has a reporter for cells in G1 or G2/S. Cells can then either continue or die in either phase. For now, we'd like to evaluate the collected data on the one state model.

**Comment by Farnazmdi** [comment]
Going on in another repo.

**Comment by aarmey** [comment]
@Farnazmdi we're using these emissions in the one state model, but they should also be used here.

**Comment by Farnazmdi** [comment]
@aarmey  Dr. Meyer, for this one, we should replace the current gamma distribution with two gamma distributions for G1 and G2 phase, then tau = time_G1 + time_G2, right?
We should not have a gamma distribution for the lifetime (what we have now), and two other distributions for G1 and G2. I mean "replacing the one gamma distribution with two gamma distributions" is intended, right?

**Comment by Farnazmdi** [comment]
If we keep the scale of G1 and G2 distributions the same, then we can say the summation of the two gamma random variables come from a new gamma distribution which we know the parameters. 
I think it is reasonable to keep the `scale` parameter for G1 and G2 the same, do you agree with it?

**Comment by Farnazmdi** [comment]
![image](https://user-images.githubusercontent.com/34812750/64218610-3e1c8f80-ce77-11e9-82a8-ea13aa5c63f9.png)

**Comment by aarmey** [comment]
I think ideally we'll want the capability to do both. The Heiser lab data will likely be stratified by cell cycle phase, while the simple cell lifetime model is simpler to explain the model.

**Comment by Farnazmdi** [comment]
Ok, I will keep both and let the user decide which one to use. Thanks.

**Comment by Farnazmdi** [comment]
#167
