### ISSUE TITLE
Good opportunity for using 'multiprocessing'

### ISSUE THREAD

**Issue by shak360** [meyer-lab/lineage-growth#99]
Good opportunity for using 'multiprocessing': https://docs.python.org/2/library/multiprocessing.html

_Originally posted by @aarmey in https://github.com/meyer-lab/lineage-growth/pull/93_

**Comment by namn12** [comment]
doesnt multiprocessing only work if your tasks are not dependent on one another. in this case, we have to evaluate each cell in a particular order depending on its position on the tree, so if we assign chunks of cells to processes, they wont run calculations on them in the order we need. or am i wrong?

**Comment by aarmey** [comment]
Generally, yes, parallel processing is only going to work if there are chunks of a task that can execute independently. For example, during your expectation step, each entire lineage is independent, and so you could split up the task of assignment to separate processes for each lineage.

**Comment by aarmey** [comment]
What I meant in the earlier issue is: if you look at each point on those plots, it's a completely separate run in which you made synthetic data, then fit the model. So, you could run the code for each point separately and in parallel. Each point isn't dependent upon the outcome from the last.

**Comment by shak360** [comment]
redundant with #151
